In [1]:
import numpy as np
a=np.array([2,3,4],dtype=np.int64) #可以指定形式
a.dtype

dtype('int64')

In [2]:
a

array([2, 3, 4])

In [3]:
b=np.array([[2,23,4],
            [3,42,1]]) #二維矩陣
b

array([[ 2, 23,  4],
       [ 3, 42,  1]])

In [4]:
c=np.zeros((3,4)) #生成3列4行的矩陣
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
d=np.ones((3,4),dtype=np.int64)#與上述一樣，多一個dtype
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
e=np.arange(10,20,2) #生成數列10到20，公差為2
e

array([10, 12, 14, 16, 18])

In [7]:
f=np.arange(12).reshape((3,4)) #生成一個從0到11的三列四行數列
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
g=np.linspace(1,10,20) #1~10分成二十斷的數列
g
g.reshape((5,4))#做reshape

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])